# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteLearn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Przedmioty',
            new_name='Subject',
        ),
        migrations.DeleteModel(
            name='Wykladowca',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='nazwa_przedmiotu',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
